DATASET:
  DATA_SET: hn32
  CATEGORY_NUM: 2
  CROP_SIZE: 32
  PATCHES_NUM: 4000
  TRAIN_NUM: 12750
  VAL_NUM: 4250
  OVERLAP: True
  SHOW_ALL: True
SEARCH:
  SEARCH_ON: False
SOLVER:
  TRAIN:
    MAX_ITER: 100000
  CHECKPOINT_PERIOD: 500
  VALIDATE_PERIOD: 500
DATALOADER:
  NUM_WORKERS: 4
  BATCH_SIZE_TRAIN: 6
  BATCH_SIZE_TEST: 6
MODEL:
  META_ARCHITECTURE: trainnet
OUTPUT_DIR: output

